export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_ALL_POST = 'GET_ALL_POST';
export const CREATE_ONE_POST = 'CREATE_ONE_POST';
export const UPDATE_ONE_POST = 'UPDATE_ONE_POST';
export const DELETE_ONE_POST = 'DELETE_ONE_POST'